listener 1883
protocol mqtt

listener 8083
protocol websockets
certfile /etc/mosquitto/certs/fullchain.pem
keyfile /etc/mosquitto/certs/privkey.pem

auth_plugin /etc/mosquitto/go-auth.so
auth_opt_backends http
auth_opt_http_host localhost
auth_opt_http_port 3000
auth_opt_http_getuser_uri  /auth/user
auth_opt_http_aclcheck_uri /auth/acl
auth_opt_http_response_mode status
